# Generated by Django 2.1.5 on 2019-04-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0002_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
