# Generated by Django 2.1.5 on 2019-04-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0007_auto_20190412_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='idd',
            field=models.IntegerField(default=1),
        ),
    ]
