# Generated by Django 2.1.5 on 2019-04-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0008_teacher_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='idd',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
