# Generated by Django 2.1.5 on 2019-04-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0012_review_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author_name',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
