# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:latest

cache:
  paths:
  - ~/.cache/pip/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - python -V                                   # Print out python version for debugging
  - pip install -r requirements.txt

stages:
  - test
  - style

testing:
    stage: test
    script: 
        python manage.py test
test:
  script:
  - python manage.py test
