# Generated by Django 2.1.5 on 2019-05-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_median_raiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
