# Generated by Django 2.1.5 on 2019-05-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_text_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='kol_rating',
            field=models.IntegerField(default=0),
        ),
    ]
