# Generated by Django 2.1.5 on 2019-05-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_teacher_kol_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_median_raiting',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_median_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
