# Generated by Django 2.1.5 on 2019-05-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_auto_20190525_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_review',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Text_review',
        ),
    ]
