# Generated by Django 2.1.5 on 2019-05-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_auto_20190525_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_obj',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
